configuration: Release
image: Visual Studio 2017
pull_requests:
  - do_not_increment_build_number: true
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_buid:
  # Display .NET Core version
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/src.csproj --verbosity m
build:
  project: OpenMovieDatabaseNetClient.sln
  verbosity: normal
  publish_nuget: true
  publish_nuget_symbols: true

#tests
test:
  # all except categories to test
  categories:
    except:
      - Integration
    
#Push to nuget
deploy:
    provider: NuGet
    api_key:
        secure: wO5eiWkOc3xv1qM1mChKx6weYq9h795U6u5NJg6kqwdSgsXZVCXjQJk6G05MuPKC
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      branch: master
    