configuration: Release
image:
    Visual Studio 2017
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  - cmd: dotnet restore ./OpenMovieDatabaseNetClient.sln --verbosity m
dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'
build:
  project: OpenMovieDatabaseNetClient.sln
  verbosity: normal
  publish_nuget: true
  publish_nuget_symbols: true

#tests
test:
  assemblies:
    only:
        - OpenMovieDatabase.Client.Test.dll
  # all except categories to test
  categories:
    except:
      - Integration
    
#Push to nuget
deploy:
    provider: NuGet
    api_key:
        secure: p29F21IZFy2nYYvu4elqX/7wqm4be6J6V0dDdYyGXYCW4BvbGTx0UdIsblkg8/33
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      branch: master
    
